import { initDialogs } from "./ui/dialogs.js";
import { initMessageMenu } from "./features/chat/message-menu.js";
import { initKeyboard } from "./ui/keyboard.js";
import { initSplash } from "./ui/splash.js";
import { initTheme } from "./ui/theme.js";
import { initMoreMenu } from "./ui/more-menu.js";
import { initLanguage } from "./features/language/language.js";
import { initAuthForm } from "./features/auth/auth-form.js";
import { initPresence } from "./features/presence/presence.js";
import { initReadState } from "./features/chat/read-state.js";
import { initVerifyEmail } from "./features/auth/verify-email.js";
import { initSession } from "./features/auth/session.js";
import { initFindContact } from "./features/contacts/find-contact.js";
import { initProfile } from "./features/profile/profile.js";
import { initUserProfile } from "./features/profile/user-profile.js";
import { initEditProfile } from "./features/profile/edit-profile.js";
import { initAvatar } from "./features/profile/avatar.js";
import { initSettings } from "./features/settings/settings.js";
import { initChatList } from "./features/chat-list/chat-list.js";
import { initChatSession } from "./features/chat/chat-session.js";
import { initForward } from "./features/chat/forward.js";
import { initReply } from "./features/chat/reply.js";
import { initOutbox } from "./features/chat/outbox.js";
import { initComposer } from "./features/chat/composer.js";
import { initEmoji } from "./features/chat/emoji.js";
import { initAttachments } from "./features/chat/attachments.js";
import { initVoiceRecorder } from "./features/chat/voice-recorder.js";
import { initMediaViewer } from "./features/chat/media-viewer.js";
import { initNotify } from "./features/notifications/notify.js";
import { initServiceWorker } from "./features/notifications/service-worker.js";
import { initScroll } from "./features/chat/scroll.js";
import { initGroupCreate } from "./features/groups/group-create.js";
import { initGroupInfo } from "./features/groups/group-info.js";
import { initBlock } from "./features/block/block.js";
import { initReport } from "./features/report/report.js";
import { initChatMenu } from "./features/chat/chat-menu.js";
import { initBlockedList } from "./features/settings/blocked-list.js";
import { initDeleteAccount } from "./features/auth/delete-account.js";
import { initTerms } from "./features/auth/terms.js";
import { initCalls } from "./features/calls/calls.js";
import { initNativeBridge } from "./features/native/native-bridge.js";

initDialogs();
initMessageMenu();
initKeyboard();
initSplash();
initTheme();
initMoreMenu();
initLanguage();
initAuthForm();
initPresence();
initReadState();
initVerifyEmail();
initSession();
initFindContact();
initProfile();
initUserProfile();
initEditProfile();
initAvatar();
initSettings();
initChatList();
initChatSession();
initForward();
initReply();
initOutbox();
initComposer();
initEmoji();
initAttachments();
initVoiceRecorder();
initMediaViewer();
initNotify();
initServiceWorker();
initScroll();
initGroupCreate();
initGroupInfo();
initBlock();
initReport();
initChatMenu();
initBlockedList();
initDeleteAccount();
initTerms();
initCalls();
initNativeBridge();
